# Generated by Django 3.1.7 on 2021-03-11 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Place')),
                ('memo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Memo')),
                ('friend_name', models.ManyToManyField(to='friend.Friend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
    ]
