# Generated by Django 3.1.7 on 2021-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_remove_friend_age'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='friend_name',
            field=models.ManyToManyField(blank=True, null=True, to='friend.Friend'),
        ),
    ]
