# Generated by Django 3.1.7 on 2021-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_remove_friend_age'),
        ('event', '0002_auto_20210314_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='friend_name',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='friend.Friend'),
        ),
    ]
