# Generated by Django 3.1.7 on 2021-03-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='age',
        ),
    ]
