# Generated by Django 3.1.7 on 2021-03-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_remove_friend_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_name',
            field=models.CharField(max_length=200, verbose_name='Friend Name'),
        ),
    ]
